#!/bin/bash
#SBATCH --partition sumo
#SBATCH -n 8
#SBATCH --time=36000
#SBATCH --export=ALL
#SBATCH --gres=gpu:1
#SBATCH --mail-user='gubaidulinvadim@gmail.com'
#SBATCH --mail-type=begin,end,requeue
#SBATCH --error=/home/sources/physmach/gubaidulin/err/chroma_scan.err
module load tools/singularity/current
singularity exec --no-home -B /lustre/scratch/sources/physmach/gubaidulin/delphi:/home/dockeruser/delphi /lustre/scratch/sources/physmach/gubaidulin/delphi.sif python /home/dockeruser/delphi/run_delphi.py  --filename Zydip.dat --ID_state open --sigma_z 9e-12 --plane vertical --scan_type sb_chromaticity --current 0.0012 --chromaticity 0.0 --min_value 0.1 --max_value 5.0 --n_scan_points 50
